config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root 'welcome#index'

  namespace :admin do
    devise_for :users,
               #path: "auth",
               #path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' },
               controllers: { registrations: 'admin/registrations', sessions: 'admin/sessions' }

    root 'welcome#index'
    resources :categories, :companies
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController

  before_action :authenticate_admin_user!
  layout "admin"
  
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :get_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_path, notice: "Categoría creada exitósamente" }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_category_path(@category), notice: "Categoría actualizada exitósamente" }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_path }
    end
  end

  private
  def get_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end


end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::AdminController

  def index
    @companies = Company.all
  end
end

app/controllers/admin/registrations_controller.rb
class Admin::RegistrationsController < Devise::RegistrationsController

  before_action :configure_permitted_parameters, :only => [:create]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password) }
  end

end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ::Devise::SessionsController

  layout "admin_login"

  protected

  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/admin/welcome_controller.rb
class Admin::WelcomeController < Admin::AdminController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
  <div class="form-group row">
    <%= f.label :name, "Nombre", :class => "col-sm-4 col-form-label" %>
    <div class="col-sm-8">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>

  <div class="form-actions row">
    <div class="col-sm-12">
      <div class="float-right">
        <%= link_to "Cancelar", admin_categories_path, :class => "btn btn-light" %>
        <%= f.submit "Guardar", :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="categories new">
  <h3>Editar categoría</h3>

  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="categories">
  <div class="row">
    <div class="col">
      <h3 class="float-left">
        Categorías de Recetas
      </h3>
      <div class="float-right">
        <%= link_to new_admin_category_path, :class => "btn btn-primary" do %>
          <span>
            <i class="fa fa-plus"></i> Agregar nueva categoría
          </span>
        <% end %>
        <%#= link_to admin_recipes_path, :class => "btn btn-light" do %>
<!--          <span>-->
<!--            <i class="fa fa-list"></i> Ver todas las recetas-->
<!--          </span>-->
        <%# end %>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Editar</th>
            <th scope="col">Eliminar</th>
          </tr>
        </thead>
        <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td>
              <%= link_to  edit_admin_category_path(category) , :class => "btn btn-primary btn-outline" do %>
                <span>
                  <i class="fa fa-edit"></i> Editar
                </span>
              <% end %>
            </td>
            <td>
              <%= link_to "#", :class => "btn btn-outline-danger",
                  :data => { :toggle => "modal", :target => "#deleteModal#{category.id}"} do %>
                <span>
                  <i class="fa fa-trash-alt"></i> Eliminar
                </span>
              <% end %>
              <div class="modal fade" id="deleteModal<%=category.id%>" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">Eliminar Categoria</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      ¿Está seguro que desea eliminar la categorias
                      <strong><%= category.name %>? Recuerde que se eliminaran todas las empresas de esta categoria </strong>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button>
                      <%= link_to "Eliminar", admin_category_path(category) ,  method: :delete, class: "btn btn-danger" %>
                    </div>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="categories new">
  <h3>Nuevo categoría</h3>

  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/show.html.erb
<div class="categories edit">
  <h3>Editar categoría</h3>

  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
<div>

app/views/admin/companies/index.html.erb
<div class="categories">
  <div class="row">
    <div class="col">
      <h3 class="float-left">
        Categorías de Recetas
      </h3>
      <div class="float-right">
        <%= link_to new_admin_category_path, :class => "btn btn-primary" do %>
          <span>
            <i class="fa fa-plus"></i> Agregar nueva categoría
          </span>
        <% end %>
        <%#= link_to admin_recipes_path, :class => "btn btn-light" do %>
<!--          <span>-->
<!--            <i class="fa fa-list"></i> Ver todas las recetas-->
<!--          </span>-->
        <%# end %>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Editar</th>
            <th scope="col">Eliminar</th>
          </tr>
        </thead>
        <tbody>
        <% @companies.each do |compnay| %>
          <tr>
            <td><%= compnay.name %></td>
            <td>
              <%= link_to  edit_admin_category_path(compnay) , :class => "btn btn-primary btn-outline" do %>
                <span>
                  <i class="fa fa-edit"></i> Editar
                </span>
              <% end %>
            </td>
            <td>
              <%= link_to "#", :class => "btn btn-outline-danger",
                  :data => { :toggle => "modal", :target => "#deleteModal#{category.id}"} do %>
                <span>
                  <i class="fa fa-trash-alt"></i> Eliminar
                </span>
              <% end %>
              <div class="modal fade" id="deleteModal<%=category.id%>" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">Eliminar Categoria</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      ¿Está seguro que desea eliminar la categorias
                      <strong><%= category.name %>? Recuerde que se eliminaran todas las empresas de esta categoria </strong>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-light" data-dismiss="modal">Cancelar</button>
                      <%= link_to "Eliminar", admin_category_path(category) ,  method: :delete, class: "btn btn-danger" %>
                    </div>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Ya está registrado? Inicie sesión", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Registrarme", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Olvidé mi contraseña", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/admin/welcome/index.html.erb
<div>Administrador</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-white bg-white" style="padding: 0 1rem">
    <div class="container">
      <a class="navbar-brand" href="#" style="padding: 0">
        SIN NOMBRE
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Quienes Somos <span class="sr-only">(current)</span></a>
          </li>
          <% Category.all.each do |category| %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= category.name %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
          <% end %>

        </ul>
      </div>
    </div>  
  </nav>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bioselva</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag params[:controller] %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous" />
  </head>

  <body>
    <div class="Sidebar">
      <div class="Sidebar__logoWrapper">
        Bioselva.pe Admin
      </div>
      <div class="Sidebar__content">
        <ul class="Sidebar__menu">
          <li>
            <a href="#" class="Sidebar__menuItem">Dashboard</a>
          </li>
          <li>
            <%= link_to "Categories", admin_categories_path, :class => "Sidebar__menuItem", :id => "sidebar_products" %>
          </li>
          <li>
            <%= link_to "Empresas", admin_companies_path, :class => "Sidebar__menuItem", :id => "sidebar_recipes" %>
          </li>
<!--          <li>-->
            <%#= link_to "Beneficios", admin_utilities_path, :class => "Sidebar__menuItem", :id => "sidebar_benefits" %>
<!--          </li>-->
<!--          <li>-->
            <%#= link_to "Pedidos", admin_orders_path, :class => "Sidebar__menuItem", :id => "sidebar_orders" %>
<!--          </li>-->
<!--          <li>-->
            <%#= link_to "Articulos", admin_articles_path, :class => "Sidebar__menuItem", :id => "sidebar_articles" %>
<!--          </li>-->
<!--          <li>-->
            <%#= link_to "Portadas", admin_covers_path, :class => "Sidebar__menuItem" %>
<!--          </li>-->
<!--          <li>-->
            <%#= link_to "Clientes", admin_customers_path, :class => "Sidebar__menuItem", :id => "sidebar_customers" %>
<!--          </li>-->
          <li>
            <%= link_to "Cerrar sesión", destroy_user_session_path, :method => :delete, :class => "Sidebar__menuItem" %>
          </li>
        </ul>
      </div>
    </div>
    
    <div class="page-content">
      <div class="container-fluid">
        <div class="row">
          <div class="session-flash">
            <% if notice %>
              <div class="alert alert-success alert-dismissable">
                <div class="alert-icon">
                  <i class="far fa-check-circle"></i>
                </div>
                <div class="alert-message">
                  <%= notice.html_safe %>
                </div>
              </div>
            <% end %>
            <% if alert %>
              <div class="alert alert-danger alert-dismissable">
                <%= alert %>
              </div>
            <% end %>
          </div>
        </div>
        <%= yield %>
      </div>
    </div>
  </body>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'admin/admin' %>
  <%= javascript_include_tag 'bootstrap.min' %>
  <%= javascript_include_tag params[:controller] %>
</html>

app/views/layouts/admin_login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bioselva</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous" />
  </head>

  <body class="admin-auth">
    <main role="main">
      <div class="container-fluid" id="main-content">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyTemplate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main role="main">
      <div class="container-fluid" id="main-content">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= image_tag "aceite_banner.jpg", :class => "second-slide", :alt => "Second slide" %>
              <div class="container">
  <!--              <div class="carousel-caption text-left">-->
  <!--                <h1>Aceite de Coco</h1>-->
  <!--                <p><span>Descubra uno de los grandes secretos de la amazonía peruana, Aceite de coco Bioselva.</span></p>-->
  <!--                <p><%#= link_to "Comprar", products_path, class:"btn btn-lg btn-green btn-outlined " %></p>-->
  <!--              </div>-->
              </div>
            </div>
            <div class="carousel-item">
              <%= image_tag "aceite_banner.jpg", :class => "second-slide", :alt => "Second slide" %>
               <div class="container">
  <!--              <div class="carousel-caption text-left">-->
  <!--                <h1>Harina de Coco</h1>-->
  <!--                <p><span>Exótica, dulce, fina, ligera y blanca como la nieve... Descubre la Harina de Coco Bioselva.</span></p>-->
  <!--                <p><%#= link_to "Comprar", products_path, class:"btn btn-lg btn-green btn-outlined " %></p>-->
  <!--              </div>-->
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        <%= render "layouts/header" %>
        <div class="container">
          <div class="row">
            <% if notice %>
              <div class="alert alert-success alert-dismissable" style="margin-top: 20px; width: 100%">
                <%= notice %>
              </div>
            <% end %>
            <% if alert %>
              <div class="alert alert-danger alert-dismissable" style="margin-top: 20px; width: 100%">
                <%= alert %>
              </div>
            <% end %>
          </div>
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'bootstrap.min' %>
  <%= javascript_include_tag params[:controller] %>
</html>

app/views/welcome/index.html.erb
<div>
  Contenido!!
</div>